mqtt:
  url: "tcp://70.12.245.101:1883"
  out:
    client-id: "SpringOutboundId"
    topic: "perfume/recipe"
    qos: 1
  in:
    client-id: "SpringInboundId"
    topic: "perfume/feedback"
    qos: 1

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moodrop
    username: json
    password: jsonsvalue!
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:/mappers/**/*.xml
  type-aliases-package: com.moodrop.model.dto
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

server:
  port: 8080
  address: 0.0.0.0


#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.MySQL8Dialect
#    show-sql: true
  # sql:
  #   init:
  #     mode: always
  #     separator: //
#      data-locations: classpath:data.sql

